Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://shellshock.io
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://shellshock.io
UUID: a0fad19f-570a-40bd-9ecb-dc4ceef53f51
Group: ""
Additional Applications: {}
