Title: Getaway Shootout
Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://lablockedgames.com/funblocked/getaway-shootout/index.html
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://lablockedgames.com/funblocked/getaway-shootout/index.html
UUID: bd8658c5-bbf3-42cd-9395-c9685b4e151d
Group: ""
Additional Applications: {}
