Title: OvO 2
Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://dedragames.com/games/ovo2/0.2alpha/
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://dedragames.com/games/ovo2/0.2alpha/
UUID: 79cf3c9d-5d44-4a49-91d6-9ac4c5c7211c
Group: ""
Additional Applications: {}
