Title: Drift boss
Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://www.mathplayground.com/drift-boss-v3/index.html
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://www.mathplayground.com/drift-boss-v3/index.html
UUID: 491c40bb-e0b2-45b7-9c91-cd95b6977562
Group: ""
Additional Applications: {}
