Title: Bloxd.io
Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://bloxd.io
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://bloxd.io
UUID: 4a0f79ba-40b8-4069-98bd-cfb7c9a29492
Group: ""
Additional Applications: {}
