Title: A Small World Cuip
Library: arcade
Play Mode: Single Player
Languages: en
Tags: ""
Tag Categories: ""
Source: http://v6p9d9t4.ssl.hwcdn.net/html/1643267/index.html?v=1574335048
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://v6p9d9t4.ssl.hwcdn.net/html/1643267/index.html?v=1574335048
UUID: 2c61f5a2-fb5d-4e12-8cc5-24b02e79ad7e
Group: ""
Additional Applications: {}
